### ISSUE TITLE
Change Function name

### ISSUE THREAD

**Issue by MachineLearning1090** [PZ1Sharer05/CBL#53]
Hi, I am a software engineer that has interest in using CBL. But, can you please change changeSizeOfWord(wordToBeChangedInSize, upperOrLower) to sizeOfWord().

**Comment by PZ1Sharer05** [comment]
Ok, on it!

**Comment by PZ1Sharer05** [comment]
<img width="546" alt="screenshot 2019-02-09 at 06 53 19" src="https://user-images.githubusercontent.com/44546014/52512484-8bb18080-2c37-11e9-80f8-d2362c46f19b.png">

Is this ok?

**Comment by MachineLearning1090** [comment]
Ok great!

**Comment by PZ1Sharer05** [comment]
It has been deployed. Enjoy using CBL 2.2.1. Your name has been marked there as suggester.
