### ISSUE TITLE
Delete showShortText(shortText)

### ISSUE THREAD

**Issue by MachineLearning1090** [PZ1Sharer05/CBL#55]
Hi, as you know from several minutes ago, I am ML 1090. I want to first clarrify that I am still not using CBL. I want to review it and I am interested in it. But first, the showShortText(shortText) function is a bit bothering and I think not much will use it, so would you mind if that function is deleted?

**Comment by PZ1Sharer05** [comment]
Hi ML 1090, it looks like you are quite a good fit as a contributor, my friends and I have thought that you might be a perfect role for this, why not join? I will delete that function too.

**Comment by MachineLearning1090** [comment]
Thats fine, I would join.

**Comment by PZ1Sharer05** [comment]
Nice.
