### ISSUE TITLE
Post an example of what you can make

### ISSUE THREAD

**Issue by OscarPlays404** [PZ1Sharer05/CBL#58]
I actually think that it might be a great idea to post an example code of what you can do with CBL. Does it transform like 1000 lines of code to 20 lines or is it just the same thing but with different function names?

**Comment by PZ1Sharer05** [comment]
Hi, I am the owner of this language, we have made an example code, the example code will be given with an example of the rock scissor paper game.

**Comment by PZ1Sharer05** [comment]
Well, for the 1000 lines to 20 lines, we haven't really verified it yet. However, our built-in functions makes it easier to reverse strings or repeat the words. 
NOTE: This is not Swift. This language is meant for children to use. However, anyone can use it too.

**Comment by OscarPlays404** [comment]
Ok, so what you are saying is that it just makes life easier?

**Comment by PZ1Sharer05** [comment]
Yes.
Now, I gotta go, @MachineLearning1090 . Can you help me give some more example code to explain to him.

**Comment by MachineLearning1090** [comment]
Ok sure boss.
I am going to tell you how CBL improves and automates your work with simple code @OscarPlays404 .

**Comment by MachineLearning1090** [comment]
[Python VS CBL.zip](https://github.com/PZ1Sharer05/CBL/files/2847508/Python.VS.CBL.zip)
Here is the code. 
If you ask me how I got the rock scissor paper code, it was sent to me by @PZ1Sharer05 .

**Comment by OscarPlays404** [comment]
So, thats it? 
Wait, I don't get it so CBL is just a bunch of built-in functions library or is CBL a REAL programming language???

**Comment by PZ1Sharer05** [comment]
Well, actually it is a big library made with python that will soon be an official programming language.
End of issue, your problem has been solved. Enjoy CBL 2.2.2
