### ISSUE TITLE
Check if number is even number

### ISSUE THREAD

**Issue by OscarPlays404** [PZ1Sharer05/CBL#61]
Hi, I am Edwards from OscarPlays, anyways Oscar is out, so... I want to ask if there can be a feature of checking even numbers or odd numbers using a function.
I know I can just write bunch of if statements, but since this is CBL (children's lang), could you please add that???

**Comment by MachineLearning1090** [comment]
Ok great! I will do it and release it as soon as possible!

**Comment by MachineLearning1090** [comment]
I'm done with the file, time to publish it!

**Comment by MachineLearning1090** [comment]
Enjoy version 2.2.4!
