### ISSUE TITLE
Mathematics lacks features

### ISSUE THREAD

**Issue by MachineLearning1090** [PZ1Sharer05/CBL#63]
Boss, I have an issue with the math module, well, actually not an issue, just a feature request. So I want to add a function for adding, subtracting,  modulo, and multiplication. Is that allowed???

**Comment by PZ1Sharer05** [comment]
OK, @MachineLearning1090 , you do the job...

**Comment by PZ1Sharer05** [comment]
Done? @MachineLearning1090

**Comment by MachineLearning1090** [comment]
Yea
